// Reads pre-fetched fixtures.json (generated by GitHub Actions every 30 min).
// This avoids CORS issues — the JSON lives on the same GitHub Pages origin.
// In dev, Vite serves public/ at root so the path works identically.
const FIXTURES_URL = import.meta.env.BASE_URL + 'fixtures.json'

export async function fetchWCFixtures() {
  const res = await fetch(FIXTURES_URL)
  if (!res.ok) throw new Error(`fixtures.json fetch failed: ${res.status}`)
  const json = await res.json()
  return json.fixtures
}
